// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sum.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Sum {
  public static partial class SummarizeService
  {
    static readonly string __ServiceName = "sum.SummarizeService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Sum.SumRequest> __Marshaller_sum_SumRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sum.SumRequest.Parser));
    static readonly grpc::Marshaller<global::Sum.SumResponse> __Marshaller_sum_SumResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sum.SumResponse.Parser));

    static readonly grpc::Method<global::Sum.SumRequest, global::Sum.SumResponse> __Method_Summarize = new grpc::Method<global::Sum.SumRequest, global::Sum.SumResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Summarize",
        __Marshaller_sum_SumRequest,
        __Marshaller_sum_SumResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Sum.SumReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SummarizeService</summary>
    [grpc::BindServiceMethod(typeof(SummarizeService), "BindService")]
    public abstract partial class SummarizeServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Sum.SumResponse> Summarize(global::Sum.SumRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SummarizeService</summary>
    public partial class SummarizeServiceClient : grpc::ClientBase<SummarizeServiceClient>
    {
      /// <summary>Creates a new client for SummarizeService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SummarizeServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SummarizeService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SummarizeServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SummarizeServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SummarizeServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Sum.SumResponse Summarize(global::Sum.SumRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Summarize(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Sum.SumResponse Summarize(global::Sum.SumRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Summarize, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Sum.SumResponse> SummarizeAsync(global::Sum.SumRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SummarizeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Sum.SumResponse> SummarizeAsync(global::Sum.SumRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Summarize, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SummarizeServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SummarizeServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SummarizeServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Summarize, serviceImpl.Summarize).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SummarizeServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Summarize, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Sum.SumRequest, global::Sum.SumResponse>(serviceImpl.Summarize));
    }

  }
}
#endregion
