// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: compute.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Compute {
  public static partial class ComputeAverageService
  {
    static readonly string __ServiceName = "compute.ComputeAverageService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Compute.LongComputeRequest> __Marshaller_compute_LongComputeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compute.LongComputeRequest.Parser));
    static readonly grpc::Marshaller<global::Compute.LongComputeResponse> __Marshaller_compute_LongComputeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Compute.LongComputeResponse.Parser));

    static readonly grpc::Method<global::Compute.LongComputeRequest, global::Compute.LongComputeResponse> __Method_LongCompute = new grpc::Method<global::Compute.LongComputeRequest, global::Compute.LongComputeResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "LongCompute",
        __Marshaller_compute_LongComputeRequest,
        __Marshaller_compute_LongComputeResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Compute.ComputeReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ComputeAverageService</summary>
    [grpc::BindServiceMethod(typeof(ComputeAverageService), "BindService")]
    public abstract partial class ComputeAverageServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Compute.LongComputeResponse> LongCompute(grpc::IAsyncStreamReader<global::Compute.LongComputeRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ComputeAverageService</summary>
    public partial class ComputeAverageServiceClient : grpc::ClientBase<ComputeAverageServiceClient>
    {
      /// <summary>Creates a new client for ComputeAverageService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ComputeAverageServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ComputeAverageService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ComputeAverageServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ComputeAverageServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ComputeAverageServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncClientStreamingCall<global::Compute.LongComputeRequest, global::Compute.LongComputeResponse> LongCompute(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LongCompute(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::Compute.LongComputeRequest, global::Compute.LongComputeResponse> LongCompute(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_LongCompute, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ComputeAverageServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ComputeAverageServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ComputeAverageServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_LongCompute, serviceImpl.LongCompute).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ComputeAverageServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_LongCompute, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Compute.LongComputeRequest, global::Compute.LongComputeResponse>(serviceImpl.LongCompute));
    }

  }
}
#endregion
